language: go
go:
- 1.8.x
# cache:
#   yarn: true
#   directories:
#     - node_modules
sudo: true
node_js:
  - "7"
addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - glide
      - yarn
      - build-essential
before_install:
- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
- sudo apt-get install -y nodejs
install:
- cd ${TRAVIS_BUILD_DIR}
- glide install
- go get github.com/mjibson/esc
- go get github.com/ahmetb/govvv
- go get github.com/franciscocpg/gox
- go get github.com/tcnksm/ghr
- go get github.com/sanbornm/go-selfupdate
- go get github.com/jteeuwen/go-bindata/...
- go get github.com/elazarl/go-bindata-assetfs/...
- yarn global add create-react-app grpcc
script:
- cd ${TRAVIS_BUILD_DIR} && go generate
- VERSION=$(cat ./VERSION)
- echo "VERSION = ${VERSION}"
- DIST=${TRAVIS_BUILD_DIR}/dist/dockerfile-builder/stable
- yarn install
- yarn bundle
- CGO_ENABLED=0 gox -verbose  -os="linux darwin windows" -arch="amd64" -osarch="!darwin/arm64 linux/ppc64 linux/ppc64le" -ldflags="$(govvv
  -flags) -s -w -X main.AppSecret=${APP_SECRET} -extldflags \"-static\"" -output="${DIST}/${VERSION}/{{.OS}}-{{.Arch}}/{{.Dir}}"
  .
before_deploy:
- echo "go-selfupdate generating bindiffs"
- mkdir -p ${DIST}/${VERSION}/binaries
- mkdir -p ${DIST}/latest
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/darwin-amd64   ${DIST}/${VERSION}/darwin-amd64/dockerfile-builder      ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-amd64    ${DIST}/${VERSION}/linux-amd64/dockerfile-builder       ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-ppc64le  ${DIST}/${VERSION}/linux-ppc64le/dockerfile-builder     ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/windows-amd64  ${DIST}/${VERSION}/windows-amd64/dockerfile-builder.exe
  ${TRAVIS_BUILD_DIR}/LICENSE.TXT ${TRAVIS_BUILD_DIR}/VERSION
- go-selfupdate -o ${DIST}/updates ${DIST}/${VERSION}/binaries/ ${VERSION}
- cp ${DIST}/${VERSION}/binaries/darwin-amd64  ${DIST}/latest/darwin-amd64.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-amd64   ${DIST}/latest/linux-amd64.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-ppc64le ${DIST}/latest/linux-ppc64le.tar.gz
- cp ${DIST}/${VERSION}/binaries/windows-amd64 ${DIST}/latest/windows-amd64.tar.gz
- rm -fr ${DIST}/${VERSION}/binaries
- echo "Copying latest directory to ${DIST}/${TRAVIS_COMMIT}"
- cp -r ${DIST}/latest ${DIST}/${TRAVIS_COMMIT}
after_deploy:
- cf logs dockerfile-builder --recent
- echo "releasing v${VERSION}..."
- ghr -t "$GITHUB_TOKEN" -u rai-project -r dockerfile-builder --replace "v${VERSION}"
  "${DIST}/latest"
- cd ${TRAVIS_BUILD_DIR}
deploy:
- provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: "$BLUEMIX_USERNAME"
  password: "$BLUEMIX_PASSWORD"
  organization: IBM-ILLINOIS-C3SR
  space: dev
  on:
    repo: rai-project/dockerfile-builder
- provider: s3
  access_key_id: AKIAIAFSJLCCOYB5V3EQ
  secret_access_key:
    secure: SmAJqNftOvfIClayyLJalKqkdvx/AU1ovDsDTXXgC3rTDT4JyuVUejyQYO2OCDZzMq4WAtZ1zhhNngy7T5E3LUhpUXCsOP1PaxGUkdLVPWbZ9I0SsPZbJ8u/UUyaMNlDNfumlPs9iQhhmwIAJ6ryHIzlcGbqVSGA8BPg77rLdbV4RTxEmOeICpcO1egs/7/FqCRUMTJm3765tzWKdDfCfUKImuDlif2lYmY6ED+gTNBJr2qgJ08QnJwyxnqdPoZVGdOFWE+wV1YbsdL7hkelbXlRab6ofRgd2BoyeD3X1lUBQQEISS8HEpmoH5PdrCGXwz/szWhZfdMBJ0tYqLukr9dORHTkvhs0S78Sghj/gj/c1doudZnrt9PnpMm72ZJuUTfh+b3BLZ7heMLvaMVS9uu345eSVi7Diw/Hvqvl4c7CU0RoXl6MPLw1Q258D8HQABehMsaXBF/pkB4/DuU3oQWeE3dLSQLocKQyE6uJKHD4PYt859WKT6gz9KR/iYOG705Oo/x4R1un+t5oJjbjkf6Nh5OXVpUzrxBhcuhO+tb3azVA+5UQUr2iTw/uyibcHJq48h6piAnKbe4ALkY6nN/6PImoGJ0MbArNszXyckEccuvz4iX+R2Y/nE5SFdHIxBGR6iqX9SoGLP1KooM+Cn0MsnN3wCx++y7R7jk8cqQ=
  bucket: files.rai-project.com
  local-dir: dist
  upload-dir: dist
  acl: public_read
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: rai-project/dockerfile-builder
env:
  global:
  - REPO="c3sr/demo-webserver-bluemix"
  - secure: HYq9aHpCsdGvJ/6BdYqBKRNMdHkzc0z57jcs9vI2GVR4kA46667BS9YsNxcPe6yknZaTHAmqnCAY7Bp5x0lRcFEhRQVntuseF4uF1geR1BsY3FbYn52TsB9f5t5EZNCAvroTXhzMH/+NBG952QvdUG2YIiKC3O/Cie/YYmwitSWXKy6R9Dbcqcm9quq1uUxKwjdWfbfSv/DRp1mR6fid3WwjiLuHMW04dwfKDs07rLOb5nU5bxGZvP7W86oZX+mhzayAu3AfvJxPIEpgLqd53VSWwqcG6+FSfgGrWbZB61L1B4n4NHBlw2QZNMKTBdQkCDAnhF3GTAql/0Ryd/OFAFnYTG9ANEOcVXSoPQL6y1siQtJ59BWyTR96z4RdOKkXss/F1L8vWEVysr+9lsTo7BDRf7232Z0PiKyl41/3/7g3oZXsEBWIfUcmgvruwD4rxdKnX3/2ygVWCLL7QQtd1lgoKSmXK8ZwR4PbcgPr+RvW0OdJLODta6EeNb9LBv3AhV3exWAxT4fXxQWJh9OgFI7ITCLBRudkV1ns0HoEbXnfHJJ6MJGGw9JPGuMYHYWUhhN6fRSHS8+l+Y7YO+4yoBT5cmUjbd3HR05it/uVmbZIsk9Ru+hRojU5IvElVUANMwzJsGKd8EX02HRUtmIHfOUosa2dAWSPqAQGGNiMuhA=
  - secure: vgaPQyHnp96tqKU3CcRzRmmV+ykKigePi7jjHw4HiF0dfvXKVC9Rux5kr8PFaf/14isWrb91a/pc+4c60d5AyfPq7GNHqDxGu/6Zt4MlGsY6qkaKs/gmWC7Ka8kCjwZfAWGAzFxjwBdZxOlet+EXBsXd3+UKX0LwifLUPAVs88NyYXbmW2loSXrHbKnScF0WiKZhi79085V3E8ZSGAFlNbzKok7GUKZPQXxtPjQrH24lCuyL+kdYBpHIF6ZYvLMVuPraOl1/SycNcGohq52v9g3vQ+yP5k30LWeZZKqxN+lQrfwIaSMv0CMdZ689kr8qcJwDhESE244nLdLf+pzApbyovKKvbOJ2iTSTCSTfRwW+R90eAcPYuY2rpadMgUGMqomT/tPWFOudHywH5ePIieE+cc04FWHRQ+HNQJjlvMVgvBWKZapHFlXGB+TppETKqX2/wzBGoQ7mAEI2PNTfvmlI+n6kyasuqITTAuti6R0Q2ntbbLh/ONMfUfIVhCSEhZsSYGaU4DY9adm+IiWldqXj/4qAUAYQhWPQ0RQfLHgGI531MKjBOKVa56OVx2AzelRzxQ3rFWLhV0qSYklJYfnLPFy50bffSUPTacWNjTep/V+QTKZ+WDXaUbmFhJjnXxBUOWWn+m7SGdVt8pnKX4UA7Adjnq7KA94dkaOdCeQ=
  - secure: fAgtUIQVf1KrcCOrRvymnwA5UyDw+XstT2wyO4JBHVKbKDujfYBjaCfLzSg2egjrVW1qKF2tp9UvjcqpnujxaDSWdijucMVwKlfJPQBmQmi6wTZ1C71VXLD1IRh5s7OxYrmm8i0OMdiR6mHQYTDZPHe8x7Ydz51w72bkjj5Mi/uuE1yz/OWVJgD/K9D9hr5WQ/XTm8lrE6gjlv07MV0511sCz3RVfGLobPe5Mtp+GrUU6WNtVFBGUme80IgMi2gIAmDbqb608qzrl88kl+J2mt6KcW/wWfOOu3fHmw9xtFVve0LnLzCVP+Yztl9NARSO15EjCk5GbglCi1BcTEUDOJ0UNpJearI1qIS3zjoURofXLIzslhuf/anYHiXklHAHehPQKFQgWA7a23mCB2wx5nZ7VG78Tpbh/Xu4tRK1RnWt3IThWkdkBDbG9TLdcFGgNhJvOo0UFUAfs1/Le/arawxExUW6H7t76GWGDWoIjaawqiGG4D3AjrnEertoZKxlh6xmMwdJnmDHKnS3fwL2tt1N75X+9qXgdIGdANycpZOEMRxMRNCQWbsfpHk4IwCgpZaNSrblFumCRNkC0xWmCHQy71eubqADWJp7F8BQiWxqXYkTzu3wmnMzXlfCRMHEQhNDYhsWp7zEKy77siOxn2oK//c/Ex2NIgzTPg94XCA=
